### ISSUE TITLE
Debian 'jessie' one

### ISSUE THREAD

**Issue by hrw** [zyga/os-release-zoo#1]
build@debian:~$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by zyga** [comment]
Fixed in c14a6cb13d0bf67a5a238719b9a84b43955c3890 -- thank you :-)
