### ISSUE TITLE
add missing

### ISSUE THREAD

**Issue by Shark-Linux** [zyga/os-release-zoo#25]
NAME="SharkLinux"
VERSION="SharkLinux OS (CR)"
ID=sharklinux
ID_LIKE=ubuntu
PRETTY_NAME="SharkLinux"
VERSION_ID="CR"
HOME_URL="http://www.sharklinuxos.org/"
SUPPORT_URL="http://support.sharklinuxos.org/"
BUG_REPORT_URL="http://support.sharklinuxos.org/"
VERSION_CODENAME=sharklinuxos
UBUNTU_CODENAME=xenial

**Comment by zyga** [comment]
Added in 5d5bd705b0288dc507fcbbc1ef3270ab139d5bac
