### ISSUE TITLE
License needed

### ISSUE THREAD

**Issue by jhermann** [zyga/os-release-zoo#3]
You should put up some CC license for the collection, or make it CC0.

**Comment by zyga** [comment]
I was thinking about this just now. Since the project is simply a collection of original content from various distributions I think it would be appropriate to use the original license. I will look into that.

**Comment by zyga** [comment]
On the other hand I'm not entirely sure those files are suitable for copyright protection. Most of those things are facts and the most creative part would, perhaps, be the `PRETTY_NAME`. Pulling each copyright file from each distribution might make this work a bit more cluttered so unless there's a strong desire to reproduce the original copyright file from each distribution I would like to consider using a simple and permissive license that covers the aggregation.

**Comment by jhermann** [comment]
There's this thing about "database" or "collection" copyright, and I think you should cover that for clarity, and add some blurb about "license conditions of the original content apply".

**Comment by zyga** [comment]
I'm sorry for leaving this issue open for so long. I'll add a license file shortly.

**Comment by zyga** [comment]
I just applied CC0 license to the repository. Thank you for reporting the issue!
