### ISSUE TITLE
Marker for distros that do _not_ support os-release?

### ISSUE THREAD

**Issue by jhecking** [zyga/os-release-zoo#6]
How about adding some marker for distros/versions that do not (yet) include the `/etc/os-release` file? I'm working on an installation script and want to use the `os-release` data to determine the distro/release on which the package gets installed. But certain distros/versions do not (yet) support this data, e.g. CentOS 6. So I need to have a different fall-back for these cases.

Gathering the data about which distros support os-release has been cumbersome so I appreciate the effort to document this info in a single place. I think adding info about which distros do _not_ support this feature would make the effort even more valuable.

**Comment by zyga** [comment]
That's a pretty cool idea! I wonder how to best express that?

We could list them with a different extension, e.g. `centos/centos-6.missing` or something like that?

**Comment by jhecking** [comment]
"missing" could be interpreted either as "this distro does not include os-release" or as "a sample from this distro is missing in this collection". How about "not-supported" instead?

**Comment by zyga** [comment]
Yeah, `not-supported` is okay. Let's also mention this in the README file.
